### ISSUE TITLE
Error in woosh

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Django#18]
```
Internal Server Error: /plugins/GeoSearch/version/1.6.0/download/
Traceback (most recent call last):
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./plugins/views.py", line 837, in version_download
    plugin.save(keep_date=True)
  File "./plugins/models.py", line 340, in save
    super(Plugin, self).save(*args, **kwargs)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/haystack/signals.py", line 52, in handle_save
    index.update_object(instance, using=using)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/haystack/indexes.py", line 282, in update_object
    backend.update(self, [instance])
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/haystack/backends/whoosh_backend.py", line 227, in update
    writer.commit()
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 1040, in commit
    self.writer.commit(*args, **kwargs)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 925, in commit
    finalsegments = self._merge_segments(mergetype, optimize, merge)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 830, in _merge_segments
    return mergetype(self, self.segments)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 88, in MERGE_SMALL

    writer.add_reader(reader)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 710, in add_reader
    self.add_postings_to_pool(reader, basedoc, docmap)
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 634, in add_postings_to_pool
    for item in items:
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/writing.py", line 570, in _process_posts
    for fieldname, text, docnum, weight, vbytes in items:
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/reading.py", line 432, in iter_postings
    yield (fieldname, btext, m.id(), m.weight(), m.value())
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 928, in value
    self._read_values()
  File "/home/plugins/.virtualenvs/plugins/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 1049, in _read_values
    assert isinstance(vs, bytes_type)
AssertionError
```

**Comment by rjagadeeswaran** [comment]
Any update on this error? Has it been resolved ? I am facing the same issue when trying to save to Database using django models. django-haystack==2.1.0
