### ISSUE TITLE
question mark in password kills upload_plugin.py

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/QGIS-Django#48]
Haven't had time to investigate more, but having a password with a question mark will generate this traceback:

```
Password: 
Connecting to: http://lalala:*@plugins.qgis.org:80/plugins/RPC2/
Traceback (most recent call last):
  File "./plugin_upload.py", line 115, in <module>
    main(options, args)
  File "./plugin_upload.py", line 44, in main
    xmlrpc.client.Binary(open(arguments[0]).read()))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
Makefile:81: recipe for target 'upload' failed
```

**Comment by mbernasocchi** [comment]
not even sure maybe I should file this on the pluginbuilder issue tracker?
@elpaso what do you think?

**Comment by elpaso** [comment]
Not sure... it might also be an issue in the website.

**Comment by carolinux** [comment]
@mbernasocchi getaddrinfo is called on your end and fails before managing to create a connection, so,  this doesn't have to do with the website, but rather, with how the url (which includes the authentication) is built.  ('?' being a special character for urls )

I suggest to close this.
